spring:
  application:
    name: micro01
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.aybhy.mongodb.net/proyecto01?retryWrites=true&w=majority&appName=Cluster0
      
springdoc:
  api-docs:
    enable: true
    
    
##mongodb://localhost:27018/proyecto01